name: Buscar CEP

on: 
  push:
  workflow_dispatch:
    
jobs:
  buscar_cep:
    runs-on: ubuntu-latest    
    steps:
      - uses: rmnobarra/runtime-deploy@v1
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
